baseURL = 'https://example.com/'
languageCode = "en-us"
title = "Apache Flink"
enableGitInfo = false
theme = "book"

[params]
  stable  = true
  version = "1.13-SNAPSHOT"
  scalaVersion = "2.11"

[markup]
[markup.highlight]
  style = "pygments"
[markup.goldmark.renderer]
  unsafe = true

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

[languages.zh]
  languageName = 'Chinese'
  contentDir = 'content.zh'
  weight = 2
