baseURL = 'https://example.com/'
languageCode = "en-us"
title = "Apache Flink"
enableGitInfo = false
theme = "book"
IsMultiLingual = false

[params]
  # Flag whether this is a stable version or not.
  # Used for the quickstart page.
  IsStable = false
  
  # Flag to indicate whether an outdated warning should be shown.
  ShowOutDatedWarning = false

  # This are the version referenced in the docs. Please only use these variables
  # to reference a specific Flink version, because this is the only place where
  # we change the version for the complete docs when forking of a release branch
  # etc.
  # The full version string as referenced in Maven (e.g. 1.2.1)
  Version = "1.13-SNAPSHOT"

  # For stable releases, leave the bugfix version out (e.g. 1.2). For snapshot
  # release this should be the same as the regular version
  VersionTitle = "1.13-SNAPSHOT"

  # This suffix is appended to the Scala-dependent Maven artifact names
  ScalaVersion = "2.11"

  ProjectHomepage = "//flink.apache.org"

  JavaDocs = "//ci.apache.org/projects/flink/flink-docs-master/api/java/"

  ScalaDocs = "//ci.apache.org/projects/flink/flink-docs-master/api/scala/index.html#org.apache.flink.api.scala.package"

  PyDocs = "//ci.apache.org/projects/flink/flink-docs-master/api/python/"

  # DO NOT ENABLE
  # This disables the ToC for the
  # unerlying theme. Flink uses its
  # own TOC implementation.
  BookToC = false

  PreviousDocs = [
    ["1.12", "http://ci.apache.org/projects/flink/flink-docs-release-1.12"],
    ["1.11", "http://ci.apache.org/projects/flink/flink-docs-release-1.11"],
    ["1.10", "http://ci.apache.org/projects/flink/flink-docs-release-1.10"],
    ["1.9", "http://ci.apache.org/projects/flink/flink-docs-release-1.9"],
    ["1.8", "http://ci.apache.org/projects/flink/flink-docs-release-1.8"],
    ["1.7", "http://ci.apache.org/projects/flink/flink-docs-release-1.7"],
    ["1.6", "http://ci.apache.org/projects/flink/flink-docs-release-1.6"],
    ["1.5", "http://ci.apache.org/projects/flink/flink-docs-release-1.5"],
    ["1.4", "http://ci.apache.org/projects/flink/flink-docs-release-1.4"],
    ["1.3", "http://ci.apache.org/projects/flink/flink-docs-release-1.3"],
    ["1.2", "http://ci.apache.org/projects/flink/flink-docs-release-1.2"],
    ["1.1", "http://ci.apache.org/projects/flink/flink-docs-release-1.1"],
    ["1.0", "http://ci.apache.org/projects/flink/flink-docs-release-1.0"]
  ]

[markup]
[markup.highlight]
  style = "pygments"
[markup.goldmark.renderer]
  unsafe = true

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

[languages.zh]
  languageName = 'Chinese'
  contentDir = 'content.zh'
  weight = 2
